[package]
name = "ch1-lab"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[features]
default = []
nobios = [
    "sbi/nobios",
]

[dependencies]
sbi = { path = "../sbi" }
rcore-console = { path = "../console" }
