[package]
name = "user_lib"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
tg-console = { path = "../tg-console" }
tg-syscall = { path = "../tg-syscall", features = ["user"] }
customizable-buddy = "0.0.2"
