[ch2]
base = 0x8040_0000
step = 0
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
]

[ch3]
base = 0x8040_0000
step = 0x0020_0000
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "05write_a",
    "06write_b",
    "07write_c",
    "08power_3",
    "09power_5",
    "10power_7",
    "11sleep",
]

[ch4]
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "05write_a",
    "06write_b",
    "07write_c",
    "08power_3",
    "09power_5",
    "10power_7",
    "11sleep",
]

[ch5]
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "12forktest",
    "13forktree",
    "14forktest2",
    "15matrix",
    "user_shell",
    "initproc",
]

[ch6]
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "12forktest",
    "13forktree",
    "14forktest2",
    "15matrix",
    "user_shell",
    "initproc",
    "filetest_simple",
    "cat_filea",
]

[ch7]
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "12forktest",
    "13forktree",
    "14forktest2",
    "15matrix",
    "user_shell",
    "initproc",
    "filetest_simple",
    "cat_filea",
    "sig_simple",
    "sig_simple2",
    "sig_ctrlc",
    "sig_tests",
]

[ch8]
cases = [
    "00hello_world",
    "01store_fault",
    "02power",
    "03priv_inst",
    "04priv_csr",
    "12forktest",
    "13forktree",
    "14forktest2",
    "15matrix",
    "user_shell",
    "initproc",
    "filetest_simple",
    "cat_filea",
    "sig_simple",
    "sig_simple2",
    "sig_ctrlc",
    "sig_tests",
    "threads",
    "threads_arg",
    "mpsc_sem",
    "sync_sem",
    "race_adder_mutex_blocking",
    "test_condvar",
]

[ch3_exercise]
base = 0x8040_0000
step = 0x0020_0000
cases = [
    "ch3_sleep",
    "ch3_sleep1",
    "ch3_trace",
]

[ch4_exercise]
cases = [
    "ch4_mmap",
    "ch4_mmap1",
    "ch4_mmap2",
    "ch4_mmap3",
    "ch4_unmap",
    "ch4_unmap2",
    "ch4_trace",
]

[ch5_exercise]
cases = [
    "00hello_world",
    "08power_3",
    "09power_5",
    "10power_7",
    "ch3_sleep",
    "ch3_sleep1",
    "ch4_mmap",
    "ch4_mmap1",
    "ch4_mmap2",
    "ch4_mmap3",
    "ch4_unmap",
    "ch4_unmap2",
    "ch5_getpid",
    "ch5_exit0",
    "ch5_exit1",
    "ch5_spawn0",
    "ch5_spawn1",
    "ch5_setprio",
    "ch5_stride",
    "ch5_stride0",
    "ch5_stride1",
    "ch5_stride2",
    "ch5_stride3",
    "ch5_stride4",
    "ch5_stride5",
    "ch5_usertest",
    "user_shell",
    "initproc",
]

[ch6_exercise]
cases = [
]

[ch8_exercise]
cases = [
]